version: '3.8'

services:
  # Database lưu trữ Metadata và Giá chứng khoán
  postgres:
    image: postgres:15-alpine
    container_name: news_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - news_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: news_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - news_network

  neo4j:
    image: neo4j:5.12-community
    container_name: history_neo4j
    restart: always
    ports:
      - "7474:7474" # Cổng vào giao diện Web (Neo4j Browser)
      - "7687:7687" # Cổng Bolt để code Python kết nối vào
    environment:
      # Nếu cần bật lại xác thực thì dùng dòng dưới đây:
      # - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc"]
      # BỘ QUYỀN BẮT BUỘC ĐỂ APOC CÓ THỂ ĐỌC/GHI DỮ LIỆU TỪ PYTHON:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      # Chống đột tử (OOM) cho Mac: Set RAM tối đa khoảng 2GB cho Neo4j
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_initial__size=2G
      - NEO4J_dbms_memory_heap_max__size=4G
      - NEO4J_server_memory_pagecache_size=4G
    volumes:
      - neo4j_data:/data
      - neo4j_import:/import
      # ĐÃ XÓA neo4j_plugins ĐỂ TRÁNH LỖI RESTART LOOP
    networks:
      - news_network

networks:
  news_network:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
  neo4j_data:
  neo4j_import:
  # ĐÃ XÓA neo4j_plugins Ở ĐÂY LUÔN